### ISSUE TITLE
Camera attached to Headset Alias

### ISSUE THREAD

**Issue by fschmidmichels** [ExtendRealityLtd/Tilia.CameraRigs.TrackedAlias.Unity#28]
## Is your feature request related to a problem?

To work with a Canvas one has to specify an event camera. When switching camera rigs (i.e. Oculus <-> UnityXR) one has to also change the event camera in the Canvas object.

## Describe the solution you'd like

Attach a camera to the HeadsetAlias that follows the CameraRig-Cameras.

## Describe alternatives you've considered

?

## Additional context

---

**Comment by thestonefox** [comment]
You can't have a camera that follows the main active camera around otherwise you end up with 2 cameras rendering the same viewpoint.

You can call the `TrackAliasFacade.ActiveHeadsetCamera` to get the current active camera to populate the canvas if you want.

I may look into emitting an event when any of the TrackedAlias aliases change and then you could just listen to that event for changes.

**Comment by fschmidmichels** [comment]
Thank you for the help. It took me some time to implement it, but this is the solution I came up with:
`using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Tilia.CameraRigs.TrackedAlias;

public class SetCanvasCamera : MonoBehaviour
{
    
    // Start is called before the first frame update
    void Start()
    {
        GameObject trackedalias = GameObject.Find("CameraRigs.TrackedAlias");
        gameObject.GetComponent<Canvas>().worldCamera = trackedalias.GetComponent<TrackedAliasFacade>().ActiveHeadsetCamera;
    }
}`
I just have to attach this script to every canvas.
